### ISSUE TITLE
Fix the hardcoded sleep; listen for ZAP-ready status, instead

### ISSUE THREAD

**Issue by stephendonner** [stephendonner/docker-zap#1]
In https://github.com/stephendonner/docker-zap/blob/36b1cc5a6516ee75f661d72fcee97c863f7fcbff/run-docker.sh#L5 I've hard-coded a sleep 10 call, but we really should be listening for a "ZAP is ready" event/status update, and only then moving on to the next step.

**Comment by stephendonner** [comment]
@psiinon - I saw you did (something like this?) with your shell script in https://github.com/mozilla/cloudsec-zap/tree/master/amo.  Anything relatable to Python/current setup, here?  Thanks!

**Comment by psiinon** [comment]
Yeah, you can poll the ZAP API waiting for a valid response.
I'm working on a script where I use:

```
    for x in range(0, timeout):
      try:
        logging.debug ('ZAP Version ' + zap.core.version)
        break
      except IOError:
        time.sleep(1)
```

This works well.
Note that the next version of the API should support this directly: https://github.com/zaproxy/zaproxy/commit/1049e1dadcc8f278714b08d0c320a9c2d33eefa8
