### ISSUE TITLE
Remove hardcoded www.allizom.org hardcoded host and pass in host to scan, dynamically

### ISSUE THREAD

**Issue by stephendonner** [stephendonner/docker-zap#4]
Remove the for-now hardcoded hostname of https://www.allizom.org, and set us up to be able to pass in (either commandline and/or, preferably, from Jenkins) any trusted host.

**Comment by psiinon** [comment]
My suggestion - change the script to use `$1` instead of `https://www.allizom.org/en-US/firefox/` you should be able to add a jenkins job parameter and then supply that as a parameter to the script. Your script is then independent of jenkins but can still be used from it - we pass in a lot of params in this way

**Comment by stephendonner** [comment]
Per @davehunt 's suggestion, I/we changed it to (in Jenkins):

TARGET_URL="https://www.allizom.org/en-US/firefox/"

And then are using:

docker exec $CONTAINER_ID zap-cli -p 2375 open-url $TARGET_URL

Is this materially the same, @psiinon / @davehunt?

**Comment by stephendonner** [comment]
For now, https://github.com/stephendonner/docker-zap/commit/108944cdc52818b54ebde63fce5f6f50bdc06dab took a stab at this.  Once the Jenkins instance gets wider use, hopefully others will help adopt more-elegant solutions.

**Comment by psiinon** [comment]
@stephendonner - important question, does it work?? ;) I'm a bit confused with line 6 - where are you actually setting TARGET_URL to the one you want to scan? You can use `$1` etc to access the script params so I was expecting something like `TARGET_URL = $1`

**Comment by stephendonner** [comment]
Sorry for the delay; work week!

No, that only mitigated the issue of hardcoding in the www.allizom.org hostname, of course.  I'm now taking a proper stab with your suggestion :-)

**Comment by stephendonner** [comment]
Arg; I'll have to take a look at injecting environment variables, likely with https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin and @davehunt's help (unless you'd like to take a stab, @psiinon ?)
